### ISSUE TITLE
How to show contents?

### ISSUE THREAD

**Issue by rainyer** [scherersoftware/cake-model-history#1]
I have installed the plugin step by step as you guys described in the documentations, but I don't understand how can I show the data that has been saved in the modelhistory table, because  the plugin files are created in vendor/pluginDirectory,  my doubt  is how can I fetch the data to a view in my main src/template?

**Comment by felixkempf** [comment]
Thanks for reaching out. We apparently missed something in our documentation.

For the modelHistoryArea to fetch its data, add the 'ModelHistory' component to the baseComponents property in your Frontend.AppController under `/webroot/js/app/app_controller.js`.
If you haven't set up the FrontendBridge yet, follow [these steps](https://github.com/scherersoftware/cake-frontend-bridge). There you will also find a template for this file.

Make sure `app_controller.js` is loaded on the page where you want to show the modelHistoryArea.
Then the ModelHistory JS-Component will make AJAX requests to /model_history/ModelHistory/index/$modelName/$primaryKey according to the $entity you gave the helper method and populate the modelHistoryArea by itself.

**Comment by felixkempf** [comment]
The missing part was added to the README. 

For the lack of further questions I'm closing this issue.
